### ISSUE TITLE
Add more words in `audiences.text` and `ideas.txt`

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/startup-cli#1]
Create additional audiences and ideas for the startup-cli generator.

**Comment by jaredstevick** [comment]
i'll take this one

**Comment by zeroxenator** [comment]
i have few ideas as well, one question though... are these supposed to be a serious or funny idea?

**Comment by maaslalani** [comment]
@zeroxenator I'd say lets do some funny ones 🤪
