### ISSUE TITLE
Implement a new command `name`

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/startup-cli#2]
In addition to the idea generator, startup-cli should have a name generator which accepts a parameter and then generates a random name related to that word.

**Comment by smokyabdulrahman** [comment]
i will handle this. However, could you elaborate more on this, please?

**Comment by maaslalani** [comment]
@smokyabdulrahman Currently startup-cli only performs idea generation. I would like startup-cli to eventually become a CLI that does a bunch of cool things. One of them being a startup name generation. This name generation could simulate something like [namelix](https://namelix.com/app/?keywords=startup).

So a user would type a command like
```
startup-cli name startup
```
and `startup-cli` would return a name or list of names
```
- Startupza
- Startify
- Smartup
- Upstart
```
Obviously these names won't be perfect, but should be somewhat good and funny.

**Comment by maaslalani** [comment]
If you do implement this document it and add the command to the `help` display so users know how to use it :)

**Comment by smokyabdulrahman** [comment]
Got it.

**Comment by smokyabdulrahman** [comment]
do you have a hint on how to solve this?

what i am doing now is filtering a list of words based on 2 criteria:
1- given word = word in list
2- given word.lengh = word in list.length && given word and word in list have same first and last letter.

however, the generated name doesn't always rhymes or have related meaning.

**Comment by maaslalani** [comment]
This node-module is for generating rhyming words: [`node-rhyme`](https://github.com/substack/node-rhyme).
This node-module is a dictionary that returns [`synonyms`](https://www.npmjs.com/package/synonyms).

If you _can_ avoid using dependencies that would be ideal, but sometimes it makes sense to use them if its too hard / time-consuming to rebuild on your own.

@smokyabdulrahman

**Comment by maaslalani** [comment]
@smokyabdulrahman 
Maybe some of these sites will work.
https://www.shopify.com/blog/name-generators-to-create-your-brand?utm_campaign=UTM+Tracking&utm_medium=Social&utm_source=twitter&utm_content=1535141939
